TRAIN:
  MAX_ITER: 100000
DATALOADER:
  NUM_WORKERS: 8
MODEL:
  NAME: 'mobilenetv2'
  IN_FEATURES: 1
  NUM_CLASSES: 360
  PRETRAINED: True
CRITERION:
  NAME: 'crossentropy'
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-3
  WEIGHT_DECAY: 3e-5
  MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'multistep_lr'
  GAMMA: 0.5
  MILESTONES: [20000, 55000]
DATASETS:
  TRAIN: ['FashionMNIST']
  TEST: ['FashionMNIST']
OUTPUT:
  DIR: 'outputs/mobilenetv2'