TRAIN:
  MAX_ITER: 10000
DATALOADER:
  NUM_WORKERS: 8
MODEL:
  NAME: 'mobilenet_v2'
  IN_FEATURES: 1
  NUM_CLASSES: 360
  PRETRAINED: True
CRITERION:
  NAME: 'crossentropy'
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-3
  WEIGHT_DECAY: 3e-4
  MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'multistep_lr'
  MILESTONES: [2500, 6000]
DATASETS:
  TRAIN: ['FashionMNIST', 'CIFAR100']
  TEST: ['FashionMNIST', 'CIFAR100']
OUTPUT:
  DIR: 'outputs/mobilenetv2'